apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
  namespace: dev
data:
  db_url: jdbc:postgresql://dpg-cjre8bdhe99c73ed6h40-a.singapore-postgres.render.com/appconfig
  db_user: anhdai
  db_password: jhiIBahhpqYCYgyTDq1Hylzj3koGiDBd
  application.properties: |
    application.hello=hello_world

