apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      restartPolicy: Always
      containers:
        - name: gateway-service
          image: anhdai0801/blog-gateway-service:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: CLOUD_CONFIG_URL
              value: "http://cloud-config:8080"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
