apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: dev
spec:
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      restartPolicy: Always
      containers:
        - name: cloud-config
          image: anhdai0801/blog-cloud-config:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
            - name: DB_URL
              valueFrom: 
                configMapKeyRef:
                  name: myapp
                  key: db_url
            - name: DB_SCHEMA
              value: appconfig
            - name: DB_USERNAME
              valueFrom: 
                configMapKeyRef:
                  name: myapp
                  key: db_user
            - name: DB_PASSWORD
              valueFrom: 
                configMapKeyRef:
                  name: myapp
                  key: db_password
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: cloud-config
  ports:
    - name: http
      port: 8080
      targetPort: 8080
