apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 200
      containers:
        - name: blog-app
          image: anhdai0801/blog-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 180"]
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: blog-app
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: blog-app
  ports:
    - name: http
      port: 80
      targetPort: 80

